mutation CreateUser(
    $email: String!
    $password: String!
    $first_name: String!
    $last_name: String!
    $calling_code: String!
    $country_code: String!
    $phone_number: String!
    $referrer: UUID
) {
    create_user (
        email: $email
        password: $password
        first_name: $first_name
        last_name: $last_name
        calling_code: $calling_code
        country_code: $country_code
        phone_number: $phone_number
        referrer: $referrer
    )
}

query Me {
    me {
        id
        email
        first_name
        last_name
        roles
        referral_count
        citizenship_status
    }
}

query CrackTime($password:String!) {
    crack_time(password: $password) {
        seconds
        guesses
        string
    }
}

mutation CreateCitizenshipApplication(
    $date_of_birth: Int!,
    $sex: String!,
    $first_name: String!,
    $last_name: String!,
    $skills: [String!]!,
    $occupations: [String!]!,
    $country_of_citizenship: [String!]!,
    $country_of_birth: String!,
    $country_of_residence: String!,
    $ethnic_groups: [String!]!,
) {
    create_citizenship_application (
        date_of_birth: $date_of_birth,
        sex: $sex,
        first_name: $first_name,
        last_name: $last_name,
        skills: $skills,
        occupations: $occupations,
        country_of_citizenship: $country_of_citizenship,
        country_of_birth: $country_of_birth,
        country_of_residence: $country_of_residence,
        ethnic_groups: $ethnic_groups,
    )
}

query UserCount {
    user_count
}

mutation Login($email: String!, $password: String!) {
    auth_token(email: $email, password: $password)
}